version: "3"
services:
  evaluate_extract:
    environment:
      - TZ=Asia/Shanghai
    image: dockerhub.datagrand.com/idps/extract:release_ci_20191025_49e4185
    volumes:
      - ./data/extract/conf:/extract/conf
      - ./data/extract/evaluate_log:/extract/log
      - ./data/extract_admin_api/upload:/extract/upload
      - ./data/predefined_rule_extract/evaluate_data:/extract/data
    command: bash -c "cd /extract/admin && sh start_server.sh processors.override.json"
  evaluate_auto_rule_extract_online:
    environment:
      - TZ=Asia/Shanghai
    image: dockerhub.datagrand.com/idps/auto_rule_extract:release_online_ci_20191127_eb0f362
    volumes:
      - ./data/auto_rule_extract/conf:/auto_rule_extract/auto_rule_extract/conf
      - ./data/auto_rule_extract/data:/auto_rule_extract/output
      - ./data/auto_rule_extract/evaluate_log:/auto_rule_extract/log
    command: bash -c "cd /auto_rule_extract/admin && sh start_server.sh evaluate_model evaluate_config"
  evaluate_crf_extract_online:
    environment:
    - ROLE=master
    - TZ=Asia/Shanghai
    - WORDSEG_HOST=wordseg_rpc
    - WORDSEG_PORT=8000
    - NER_HOST=ner_rpc
    - NER_PORT=8000
    - MODEL_LINKS_DIR=evaluate_model
    - CONFIG_LINKS_DIR=evaluate_config
    - MQ_USER_NAME=guest
    - MQ_USER_PASSWORD=guest
    - MQ_VHOST=/crf_extract_evaluate
    - ETCD_PARTITION=crf_extract_evaluate
    image: dockerhub.datagrand.com/idps/crf_extract:release_online_ci_20191129_b4a1bc3
    volumes:
    - ./data/crf_extract/conf:/crf_extract/crf_extract/conf
    - ./data/crf_extract/data:/crf_extract/crf_extract/output
    - ./data/crf_extract/evaluate_log:/crf_extract/crf_extract/log
  evaluate_crf_extract_online_slave:
    environment:
    - ROLE=slave
    - TZ=Asia/Shanghai
    - WORDSEG_HOST=wordseg_rpc
    - WORDSEG_PORT=8000
    - NER_HOST=ner_rpc
    - NER_PORT=8000
    - MODEL_LINKS_DIR=evaluate_model
    - CONFIG_LINKS_DIR=evaluate_config
    - MQ_USER_NAME=guest
    - MQ_USER_PASSWORD=guest
    - MQ_VHOST=/crf_extract_evaluate
    - ETCD_PARTITION=crf_extract_evaluate
    image: dockerhub.datagrand.com/idps/crf_extract:release_online_ci_20191129_b4a1bc3
    volumes:
    - ./data/crf_extract/conf:/crf_extract/crf_extract/conf
    - ./data/crf_extract/data:/crf_extract/crf_extract/output
    - ./data/crf_extract/evaluate_log:/crf_extract/crf_extract/log
    deploy:
      replicas: 4
  evaluate_fuzzy_extract_online:
    environment:
      - TZ=Asia/Shanghai
    image: dockerhub.datagrand.com/idps/fuzzy_extract:release_online_ci_20190814_fd81241
    volumes:
      - ./data/fuzzy_extract/conf:/fuzzy_extract/fuzzy_extract/conf
      - ./data/fuzzy_extract/data:/fuzzy_extract/fuzzy_extract/output
      - ./data/fuzzy_extract/evaluate_log:/fuzzy_extract/fuzzy_extract/log
    command: bash -c "cd /fuzzy_extract/admin && sh start_online.sh evaluate_model evaluate_config"
  evaluate_fields_analysis_online:
    environment:
      - TZ=Asia/Shanghai
    image: dockerhub.datagrand.com/idps/fields_analysis:release_online_ci_20190820_7d2dcec
    volumes:
      - ./data/fields_analysis/conf:/fields_analysis/fields_analysis/conf
      - ./data/fields_analysis/data:/fields_analysis/fields_analysis/data/train_result
      - ./data/fields_analysis/evaluate_log:/fields_analysis/fields_analysis/log
    command: bash -c "cd /fields_analysis/admin && sh start_online.sh evaluate_model evaluate_config"
  evaluate_diff_extract_online:
    environment:
      - TZ=Asia/Shanghai
    image: dockerhub.datagrand.com/idps/diff_extract:release_online_ci_20191120_72bf061
    volumes:
      - ./data/diff_extract/evaluate_log:/diff_extract/diff_extract/log
      - ./data/diff_extract/data:/diff_extract/diff_extract/output
      - ./data/diff_extract/conf:/diff_extract/diff_extract/conf
      - ./data/diff_extract/tmp:/diff_extract/diff_extract/tmp
      - ./data/extract_admin_api/upload:/diff_extract/diff_extract/upload
    command: bash -c "cd /diff_extract/admin && sh start_online_server.sh evaluate_model evaluate_config"
  evaluate_table_extract_online:
    environment:
      - TZ=Asia/Shanghai
      - NER_HOST=ner_rpc
      - NER_PORT=8000
    image: dockerhub.datagrand.com/idps/table_extract:release_online_ci_20191018_d7131f6
    volumes:
      - ./data/table_extract/evaluate_log:/table_extract/table_extract/log
      - ./data/table_extract/data:/table_extract/table_extract/output
      - ./data/table_extract/conf:/table_extract/table_extract/conf
      - ./data/table_extract/scripts:/table_extract/table_extract/app/scripts
      - ./data/table_extract/tmp:/table_extract/table_extract/tmp
      - ./data/extract_admin_api/upload:/table_extract/table_extract/upload
    command: bash -c "cd /table_extract/admin && sh start_online_server.sh evaluate_model evaluate_config"
  evaluate_dl_extract_online:
    image: dockerhub.datagrand.com/idps/dl_extract:release_online_ci_20191125_894cea9
    environment:
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - TZ=Asia/Shanghai
      - WORDSEG_HOST=wordseg_rpc
      - WORDSEG_PORT=19000
      - NER_HOST=ner_rpc
      - NER_PORT=19001
      - BERT_SERVER_HOST=dl-online.datagrand.cn
      - BERT_SERVER_PORT=6766
      - EXTRACT_QUEUE=evaluate_queue
    volumes:
      - ./data/dl_extract/conf:/dl_extract/conf
      - ./data/dl_extract/data:/dl_extract/output
      - ./data/dl_extract/evaluate_log:/dl_extract/log
    command: bash -c "python -m online.server 8000 evaluate_model evaluate_config evaluate_dl_extract_online"
  evaluate_dl_extract_online_worker:
    image: dockerhub.datagrand.com/idps/dl_extract:release_online_worker_ci_20191125_894cea9
    environment:
      - TZ=Asia/Shanghai
      - MQ_HOST=rabbitmq
      - MQ_PORT=5672
      - WORDSEG_HOST=wordseg_rpc
      - WORDSEG_PORT=19000
      - NER_HOST=ner_rpc
      - NER_PORT=19001
      - BERT_SERVER_HOST=dl-online.datagrand.cn
      - BERT_SERVER_PORT=6766
      - EXTRACT_QUEUE=evaluate_queue
    volumes:
      - ./data/dl_extract/conf:/dl_extract/conf
      - ./data/dl_extract/data:/dl_extract/output
      - ./data/dl_extract/evaluate_log:/dl_extract/log
    deploy:
      replicas: 8
    command: bash -c "python -m online.worker.predict_worker evaluate_model evaluate_config evaluate_dl_extract_online_worker"
